name: Snake Animation
on:
  schedule:
    - cron: "30 * * * *"  # Cada hora para pruebas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: joseluisdeveloperinit
          svg_output_path: ./output/snake.svg
          filters: "is:public"  # Solo repos públicos

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: "Update snake animation"
